import{S as g,i as u,a as h}from"./assets/vendor-eeed083b.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const v="42208037-79ed24c913e3ae53795b11edc",b=document.getElementById("search-form"),m=document.querySelector(".gallery");let i=1,d=!1,l="",f=0,a=document.getElementById("loadMoreBtn");a||(a=document.createElement("button"),a.id="loadMoreBtn",a.textContent="Load More",document.body.appendChild(a),a.style.display="none");const L=new g(".gallery a");async function p(o){try{const t=await h.get("https://pixabay.com/api/",{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:40}});return f=t.data.totalHits,i===1&&w(t.data.totalHits),t.data.hits}catch(t){return console.error("Error fetching images:",t),[]}}function w(o){o>0&&!d&&(u.success({title:"Hooray!",message:`We found ${o} images.`,timeout:2500}),d=!0)}function y(o){o.forEach(r=>{const n=document.createElement("a");n.href=r.largeImageURL,n.className="photo-card",n.innerHTML=`
<div class ="info">
            <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
            <div class="card-info">
                <div class ="card-list"><p>Likes</p> ${r.likes}</div>
                <div class ="card-list"><p>Views</p> ${r.views}</div>
                <div class ="card-list"><p>Comments</p> ${r.comments}</div>
                <div class ="card-list"><p>Downloads</p>${r.downloads}</div>
            </div></div>
        `,m.appendChild(n)}),L.refresh(),i*40>=f?(a.style.display="none",setTimeout(()=>{u.info({title:"End of Stock",message:"We are sorry, but you have reached end of search results",position:"bottomCenter",timeout:3e3})},2700)):a.style.display="block"}b.addEventListener("submit",E);async function E(o){if(o.preventDefault(),l=o.target.searchQuery.value.trim(),l){i=1,m.innerHTML="",d=!1,a.style.display="none";const t=await p(l);t.length>0?y(t):u.warning({title:"Sorry",message:"No images found for your query. Please try again."})}}a.addEventListener("click",I);async function I(){i+=1;const o=await p(l);y(o)}
//# sourceMappingURL=commonHelpers.js.map
